apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java_app
    spec:
      containers:
      - name: java_app
        image: loredanamoanga/java8_app
