apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java_app
    spec:
      containers:
      - name: java_app
        image: index.docker.io/loredanamoanga/java8_app