name: CI
on:
  pull_request:
    types: [opened]
    branches: ["deployment"]
    tags: ["autodeploy"]

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: loredanamoanga/java8-app

jobs:
compile:
  name:compile
  runs-on:ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: '8.0.0' # The JDK version to make available on the path.
              java-package: jre # (jre, jdk, or jdk+fx) - defaults to jdk
              architecture: x64 # (x64 or x86) - defaults to x64
          - run: javac helloworld.java

build-and-push:
  name: Build & Promote Image
  runs-on: ubuntu-latest
  needs: ["compile"]
    steps:
      -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: loredanamoanga/java_app:latest
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

Promote:
  needs: ["compile", "build-and-push"]
  runs-on: ubuntu-latest
  steps:
    - uses: superbrothers/close-pull-request@v3
    - uses: actions/checkout@v2
      with:
        ref: production
    - name: Reset promotion branch
      run: |
        git fetch origin master:master
        git reset --hard master
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: deployment