name: PR-linting

on:
  push:
    branches: ['master']

env:
  WORKFLOW_VERSION: workflow_version

jobs:
  linter:
    name: Linter
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy to linters
        run: |
          cp manifests/whateber-linter.xml .github/linters/sun_checks.xml
          cp manifests/whateber-linter.xml .github/linters/libxml.xml
      - name: Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_XML: true
          VALIDATE_JAVA: true
          LOG_LEVEL: TRACE
          ACTIONS_RUNNER_DEBUG: true
          IGNORE_GITIGNORED_FILES: true
          YAML_CONFIG_FILE: linters/.yaml-lint.yml