name: PR-linting

on:
  push:
    branches: ['master']

env:
  WORKFLOW_VERSION: workflow_version

jobs:
  linter:
    name: Linter
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy to linters
        run: |
          mkdir -p .github/linters/
          cp manifests/checkstyle-java-google-style.xml .github/linters/sun_checks.xml
          cp manifests/checkstyle-suppressions.xml .github/linters/checkstyle-suppressions.xml
      - name: Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_XML: true
          VALIDATE_JAVA: true
          IGNORE_GITIGNORED_FILES: true